### PR TITLE
add fsharp sample plugin project

### PR DESCRIPTION
**Pull request by NickDarvey**
Adds an fsharp sample plugin project.

It doesn't work actually right now. @mhmd-azeez, do you have any tips on how to debug this interop? [It looks like you've seen this error before](https://github.com/extism/csharp-pdk/blob/f45a59ddc6b518bcbfeee92aa5d5794ae13df11d/samples/SamplePlugin/Functions.cs#L20).

```
Extism.Sdk.Native.ExtismException: 'Call failed

Caused by:
    0: error while executing at wasm backtrace:
           0: 0xbf84f - <unknown>!<wasm function 447>
           1: 0xbbf5d - <unknown>!<wasm function 394>
           2: 0x65c1b - <unknown>!<wasm function 322>
           3: 0x61cdf - <unknown>!<wasm function 321>
           4: 0x36596a - <unknown>!<wasm function 6275>
           5: 0x20ee33 - <unknown>!<wasm function 3061>
           6: 0x210b1c - <unknown>!<wasm function 3077>
           7: 0x20f857 - <unknown>!<wasm function 3067>
           8: 0x40afb - <unknown>!<wasm function 145>
           9: 0xba9f5 - <unknown>!<wasm function 383>
          10: 0xb25e7 - <unknown>!<wasm function 322>
          11: 0x61cdf - <unknown>!<wasm function 321>
          12: 0x36596a - <unknown>!<wasm function 6275>
          13: 0x20ee33 - <unknown>!<wasm function 3061>
          14: 0x210b1c - <unknown>!<wasm function 3077>
          15: 0x20f857 - <unknown>!<wasm function 3067>
          16: 0x40afb - <unknown>!<wasm function 145>
          17: 0xba9f5 - <unknown>!<wasm function 383>
          18: 0xb25e7 - <unknown>!<wasm function 322>
          19: 0x61cdf - <unknown>!<wasm function 321>
          20: 0x36596a - <unknown>!<wasm function 6275>
          21: 0x20ee33 - <unknown>!<wasm function 3061>
          22: 0x210b1c - <unknown>!<wasm function 3077>
          23: 0x21a184 - <unknown>!<wasm function 3163>
          24: 0xe1d73 - <unknown>!<wasm function 703>
          25: 0xe1f98 - <unknown>!<wasm function 704>
          26: 0x35de - <unknown>!<wasm function 37>
          27: 0x41638d - <unknown>!<wasm function 7797>
    1: wasm trap: indirect call type mismatch'
```

### CODE REVIEW

**Comment by mhmd-azeez** [comment]
@NickDarvey thank you very much! If I add an explicit entry point in Library.fs with a printfn, it seems to work:

```fsharp
[<EntryPoint>]
let main args =
    printfn "Arguments passed to function : %A" args
    0
```

This is a temporary fix, I'll have to investigate what's going on exactly. The WASI SDK seems to really like entry points with Console.WriteLine

**Comment by NickDarvey** [comment]
> @NickDarvey thank you very much! If I add an explicit entry point in Library.fs with a printfn, it seems to work:
> 
> ```fsharp
> [<EntryPoint>]
> let main args =
>     printfn "Arguments passed to function : %A" args
>     0
> ```
> 
> This is a temporary fix, I'll have to investigate what's going on exactly. The WASI SDK seems to really like entry points with Console.WriteLine

@mhmd-azeez, oh, thanks for finding this! I'm very unfamiliar with the WASI SDK but, if you don't find a way to avoid a WriteLine, we could generate our own entry point (that calls WriteLine) similar to [how the test SDK generates one](https://github.com/microsoft/vstest/blob/836eb5a35eaac3521b558ffa7608cd9442cda854/src/package/nuspec/Microsoft.NET.Test.Sdk.targets#L61-L95).

**Comment by mhmd-azeez** [comment]
@NickDarvey very cool, I didn't know that! If we couldn't find the root cause of the wasm trap, I think that's a very good workaround.

If you're done with it, I think we can merge this PR. Then we can discuss how we are going to fix the wasm trap. Are you a member of the discord server? We have a C# PDK channel there. And maybe we should rename it to dotnet PDK :D

**Comment by NickDarvey** [comment]
> If you're done with it, I think we can merge this PR

I'm done, please merge.

>  Are you a member of the discord server? We have a C# PDK channel there.

I am not, but I'll join!

> And maybe we should rename it to dotnet PDK :D

<3

**Pull request merged**
